# Generated by Django 3.2 on 2023-01-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('completed', models.DateTimeField(blank=True)),
            ],
        ),
    ]
